//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.Controls {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HUDT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HUDT() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Controls.HUDT", typeof(HUDT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap _2dfix_wide {
            get {
                object obj = ResourceManager.GetObject("_2dfix_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap _3ddgps_wide {
            get {
                object obj = ResourceManager.GetObject("_3ddgps_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap _3dfix_wide {
            get {
                object obj = ResourceManager.GetObject("_3dfix_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ARMED 的當地語系化字串。
        /// </summary>
        public static string ARMED {
            get {
                return ResourceManager.GetString("ARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AS  的當地語系化字串。
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bat 的當地語系化字串。
        /// </summary>
        public static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_1 {
            get {
                object obj = ResourceManager.GetObject("batt_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_2 {
            get {
                object obj = ResourceManager.GetObject("batt_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_3 {
            get {
                object obj = ResourceManager.GetObject("batt_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_4 {
            get {
                object obj = ResourceManager.GetObject("batt_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_red {
            get {
                object obj = ResourceManager.GetObject("batt_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap batt_yellow {
            get {
                object obj = ResourceManager.GetObject("batt_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Cell 的當地語系化字串。
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DISARMED 的當地語系化字串。
        /// </summary>
        public static string DISARMED {
            get {
                return ResourceManager.GetString("DISARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E 的當地語系化字串。
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ekf_green {
            get {
                object obj = ResourceManager.GetObject("ekf_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ekf_red {
            get {
                object obj = ResourceManager.GetObject("ekf_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ekf_yellow {
            get {
                object obj = ResourceManager.GetObject("ekf_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 FAILSAFE 的當地語系化字串。
        /// </summary>
        public static string FAILSAFE {
            get {
                return ResourceManager.GetString("FAILSAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int FailsafeH {
            get {
                object obj = ResourceManager.GetObject("FailsafeH", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Arial 的當地語系化字串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: No GPS 的當地語系化字串。
        /// </summary>
        public static string GPS0 {
            get {
                return ResourceManager.GetString("GPS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: No Fix 的當地語系化字串。
        /// </summary>
        public static string GPS1 {
            get {
                return ResourceManager.GetString("GPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: 2D Fix 的當地語系化字串。
        /// </summary>
        public static string GPS2 {
            get {
                return ResourceManager.GetString("GPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: 3D Fix 的當地語系化字串。
        /// </summary>
        public static string GPS3 {
            get {
                return ResourceManager.GetString("GPS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: 3D dgps 的當地語系化字串。
        /// </summary>
        public static string GPS4 {
            get {
                return ResourceManager.GetString("GPS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: rtk Float 的當地語系化字串。
        /// </summary>
        public static string GPS5 {
            get {
                return ResourceManager.GetString("GPS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS: rtk Fixed 的當地語系化字串。
        /// </summary>
        public static string GPS6 {
            get {
                return ResourceManager.GetString("GPS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GS  的當地語系化字串。
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico_hud_power100 {
            get {
                object obj = ResourceManager.GetObject("ico_hud_power100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico_hud_power20 {
            get {
                object obj = ResourceManager.GetObject("ico_hud_power20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico_hud_power40 {
            get {
                object obj = ResourceManager.GetObject("ico_hud_power40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico_hud_power60 {
            get {
                object obj = ResourceManager.GetObject("ico_hud_power60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico_hud_power80 {
            get {
                object obj = ResourceManager.GetObject("ico_hud_power80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 N 的當地語系化字串。
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NE 的當地語系化字串。
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap nofix_wide {
            get {
                object obj = ResourceManager.GetObject("nofix_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap nogps_wide {
            get {
                object obj = ResourceManager.GetObject("nogps_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Not Ready to Arm 的當地語系化字串。
        /// </summary>
        public static string NotReadyToArm {
            get {
                return ResourceManager.GetString("NotReadyToArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NW 的當地語系化字串。
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap prearm_green {
            get {
                object obj = ResourceManager.GetObject("prearm_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap prearm_red {
            get {
                object obj = ResourceManager.GetObject("prearm_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Ready to Arm 的當地語系化字串。
        /// </summary>
        public static string ReadyToArm {
            get {
                return ResourceManager.GetString("ReadyToArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap rtkfixed_wide {
            get {
                object obj = ResourceManager.GetObject("rtkfixed_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap rtkfloat_wide {
            get {
                object obj = ResourceManager.GetObject("rtkfloat_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 S 的當地語系化字串。
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SAFE 的當地語系化字串。
        /// </summary>
        public static string SAFE {
            get {
                return ResourceManager.GetString("SAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SE 的當地語系化字串。
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SW 的當地語系化字串。
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap vibe_green {
            get {
                object obj = ResourceManager.GetObject("vibe_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap vibe_red {
            get {
                object obj = ResourceManager.GetObject("vibe_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap vibe_yellow {
            get {
                object obj = ResourceManager.GetObject("vibe_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 W 的當地語系化字串。
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
    }
}
